fail_fast: false
repos:
  # A lot of useful hooks for consistency and repo usage
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-symlinks
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-json
      - id: check-xml
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: docs/make.bat # Windows script requires windows-style line endings.
      - id: no-commit-to-branch
        args:
          - --branch=main
          - --branch=develop
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-typing-imports

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.0.0
    hooks:
      - id: rstcheck
        additional_dependencies:
          - sphinx~=5.3.0

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      - id: check-lockfile
        name: verify pdm.lock integrity
        entry: pdm install --check --dry-run
        language: system
        files: (pyproject.toml)|(pdm.lock)
        pass_filenames: false

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [--py37-plus]
      - id: nbqa-isort
        args: [--profile=black]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  {%- if cookiecutter.use_mypy == 'True' %}
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.901
    hooks:
      - id: mypy
        exclude: tests/
        {% if cookiecutter.command_line_interface|lower == 'click' -%}
        additional_dependencies:
          - types-click
        {%- endif %}
  {%- endif %}
